### ISSUE TITLE
Does not support DOS / Windows style new lines (CRLF).

### ISSUE THREAD

**Issue by MarekKnapek** [PhilippRados/wrecc#1]
`error: unexpected character: '\r'`
`error: found trailing tokens after preprocessor directive`

**Comment by PhilippRados** [comment]
Yes as mentioned the supported platforms currently are Unix-based, which I could only test for MacOs and Linux.
Because Windows has a different ABI I think the codegen would fail anyway.
If you want to try anyway of course you can just add `\r\n` as the newline sequence (as far as my current windows knowledge goes).

**Comment by MarekKnapek** [comment]
I don't understand. Yes, your program runs on Linux and generates programs for Linux. I'm not running your program on Windows, I also don't want to generate Windows executables. I'm running your program on Linux, expecting to generate a Linux binary. I want to compile my cross-platform C source code, that happens to have CRLF new lines.

> If you want to try anyway of course you can just add `\r\n` as the newline sequence (as far as my current windows knowledge goes).

I don't understand this, where should I add what?

**Comment by PhilippRados** [comment]
Ok my bad then I misunderstood you. 
I'll take a look at it then.
But it should be a simple fix by replacing '\r’\n' with only ’\n' here:
https://github.com/PhilippRados/wrecc/blob/master/wrecc_compiler/src/preprocessor/scanner.rs#L123-L128

**Comment by PhilippRados** [comment]
Ok I fixed it in the last commit.
